### ISSUE TITLE
invoke 参数 data 传递不符合预期

### ISSUE THREAD

**Issue by bear-ei** [midwayjs/midway-faas#107]
./f.yml

```
service: serverless-hello-world

provider:
  name: aliyun

functions:
  index:
    handler: index.handler
    events:
      - http:
          method: post

package:
  artifact: code.zip
```
./test/index.test.ts

```
import { invoke } from '@midwayjs/serverless-invoke'
import * as assert from 'assert'
import { join } from 'path'

describe('/test/index.test.ts', () => {
  it('invoke', async () => {
    const result: any = await invoke({
      functionName: 'index',
      functionDir: join(__dirname, '../'),
      data: [
        {
          headers: { 'Content-Type': 'text/json' },
          method: 'POST',
          path: '/test',
          body: {
            name: 'test'
          }
        }
      ]
    })
    assert(/hello world/.test(result))
  })
})
```

./src/index.ts

```
import {
  FaaSContext,
  func,
  inject,
  provide,
  FunctionHandler
} from '@midwayjs/faas'

@provide()
@func('index.handler')
export class IndexService implements FunctionHandler {
  @inject()
  ctx: FaaSContext // context

  async handler() {
    /**
     * expect { 'Content-Type': 'text/json' }
     * actual { host: '127.0.0.1:55131','user-agent': 'curl/7.64.1'}
     */
    console.info(this.ctx.request.headers)

    /**
     * expect POST
     * actual GET
     */
    console.info(this.ctx.request.method)

    /**
     * expect /test
     * actual /
     */
    console.info(this.ctx.request.path)

    /**
     * expect { name: 'test' }
     * actual undefined
     */
    console.info(this.ctx.request.body)

    return 'hello world'
  }
}
```
