### ISSUE TITLE
如何设置环境变量

### ISSUE THREAD

**Issue by bear-ei** [midwayjs/midway-faas#99]
在Fun 规范中可以通过 EnvironmentVariables 属性进行配置

```
  EnvironmentVariables:
          OSSEndpoint: oss-cn-hangzhou.aliyuncs.com
          BucketName: fun-local-test
```
在midway-faas中应该怎么实现类似的设置。 

相关文档没有找到。

**Comment by czy88840616** [comment]
全局环境变量么，是不是可以直接在平台配置？

**Comment by bear-ei** [comment]
单个函数下的环境变量，可以通过平台配置。  但是需要函数发布创建后才可以配置。 如果使用Fun 作为函数计算部署的工具，可以在 template.yml 中的EnvironmentVariables 属性进行配置。 不知道midway-faas是否具备相关能力可以通过f.yml配置环境变量。

```
fun template.yml

ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  FunDemo:
    Type: 'Aliyun::Serverless::Service'
    envdemo:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        CodeUri: ./
        Runtime: python2.7
        EnvironmentVariables:  // 单个函数环境变量配置
          OSSEndpoint: oss-cn-hangzhou.aliyuncs.com
          BucketName: fun-local-test
```

**Comment by czy88840616** [comment]
明白了，技术上没啥问题，口子也有，不过就是把一些秘钥，token配在yml里总觉得有点奇怪。。

**Comment by bear-ei** [comment]
emmm...  最近使用midway-faas最大的困扰就是环境配置上的问题，从midway转过来总感觉特别别扭。  函数计算文档那边都是推荐使用Fun或fc-sdk来解决这个问题。

**Comment by czy88840616** [comment]
恩，我们希望能够和传统 midway web 开发保持接近，你说的环境配置就是 `config.default.ts` 这种么？

**Comment by bear-ei** [comment]
是的 config.local.ts 和 config.prod.ts 配置的开发环境和生产环境这样的环境配置。  在函数计算中目前只能通过发布函数后在平台手动配置。 

目前我这边需要通过api网关发布测试环境，预上线环境。 所以每次都要手动配置工作量很大。

**Comment by czy88840616** [comment]
这个其实已经支持了，文档我还在整理

https://www.yuque.com/midwayjs/faas/env_config

**Comment by czy88840616** [comment]
支持全局环境变量以及单函数环境变量。

```yaml
service:
  name: serverless-hello-world

provider:
  name: aliyun
  environment:
    GLOBAL_PASS: admin

functions:
  index:
    handler: index.handler
  index2:
    handler: index2.handler
    environment:
      MYSQL_USER: root
      MYSQL_PASS: pass

package:
  artifact: code.zip

```
